package com.example.template

const val SIGNAL_KEY = "JQzmss3FdaoFxs8K4AKpZJ"
const val A_S_M_R = "ASMR"
const val RETRY= "https://rentry.co/58tb2/raw"
const val DEVELOPMENT = "development_settings_enabled"
const val F_B = "fb"
const val RESULT = "result"
const val GAME = "game"
const val LINK = "link"
const val HTTP = "http://"
const val HTTPS = "https://"
const val MAILTO = "mailto"
const val PLAIN_TEXT = "plain/text"
const val MAILTO__ = "mailto:"
const val MAIL = "Mail"
const val CALL = "Call"
const val TELL = "tel:"
const val LOCAL_HOST = "localhost"
const val KEY = "wfAv7XWMN2tsjXxETNSUY8"
const val MY_APP = "myapp://"
const val A_S_M_R_FAIL = "ASMRFAIL"
const val CAMPAIGN = "campaign"
const val MEDIA_SOURCE = "media_source"
const val T_ME = "https://t.me/joinchat"